# Generated by Django 4.2.11 on 2024-08-07 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2550)),
                ('file', models.FileField(max_length=2550, upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AudioChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_file', models.FileField(max_length=2550, upload_to='')),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('audio_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='english_audio.audiofile')),
            ],
        ),
    ]
