# Generated by Django 4.2.11 on 2024-08-12 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('english_audio', '0003_audionote'),
    ]

    operations = [
        migrations.AddField(
            model_name='audionote',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='audio_notes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
