name: Build, Deploy, and Dockerize

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-dockerize:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Build Vue frontend
      working-directory: ./web 
      run: |
        npm ci
        npm run build

    - name: Copy Vue build to Django static
      run: |
        mkdir -p ./api/static  # Adjust this path to your Django project's static directory
        cp -r ./web/dist/* ./api/static/

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./api 
        file: ./api/Dockerfile  

