name: Publish Package

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-dockerize:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
      
    - name: Install dependencies
      working-directory: ./api
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Build Vue frontend
      working-directory: ./web 
      run: |
        npm ci
        npm run build

    - name: collect static
      working-directory: ./api
      run: |
        mkdir -p ./api/staticfiles
        python manage.py collectstatic --noinput

    - name: Copy Vue build to Django static
      run: |
        mkdir -p ./api/staticfiles
        cp -r ./web/dist/* ./api/staticfiles/

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build audio_practice image
      run: |
        docker build . --file Dockerfile -t ghcr.io/swuecho/audio_practice:${GITHUB_REF#refs/tags/}
      working-directory: api

    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push API image to GitHub Container Registry
      run: |
        docker push ghcr.io/swuecho/audio_practice:${GITHUB_REF#refs/tags/}
        docker tag ghcr.io/swuecho/audio_practice:${GITHUB_REF#refs/tags/} ghcr.io/swuecho/audio_practice:latest
        docker push  ghcr.io/swuecho/audio_practice:latest

